// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzooqrfnurkvhgoymbxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6b29xcmZudXJrdmhnb3ltYnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDA5NDQsImV4cCI6MjA3MTM3Njk0NH0.3zik1bmB6GRzB2_7aKmAfbG8VsRRN2n0iXcxen5nqqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});